version: '3.9'

services:
  frontend:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "3040:3000"
    command: sh -c "npm run dev"
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "front-sample4-swagger-ui"
    ports:
      - "8003:8080"
    volumes:
      - ./api/bundle.json:/api.json
    environment:
      SWAGGER_JSON: /api.json
  swagger-api:
    image: stoplight/prism:3
    container_name: "swagger-api"
    ports:
      - "8004:4010"
    command: mock -h 0.0.0.0 /api.json
    volumes:
      - ./api/bundle.json:/api.json
